# Generated by Django 3.1.2 on 2021-01-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('taken', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('Subgroup', models.CharField(max_length=10)),
                ('leader', models.CharField(max_length=200)),
                ('member_name_1', models.CharField(max_length=200)),
                ('member_name_2', models.CharField(max_length=200)),
                ('member_name_3', models.CharField(max_length=200)),
                ('member_name_4', models.CharField(max_length=200)),
                ('member_name_5', models.CharField(max_length=200)),
                ('project_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemSelector.system')),
            ],
        ),
    ]
